//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
public class ResourceType
{
	public ResourceType()
	{

	}
	public ResourceType(string un, string fn)
	{
		UniqueName = un;
		FriendlyName = fn;
	}
	public string UniqueName = "";
	public string FriendlyName = "";
}
