//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Xml;
using System.Xml.Serialization;
using System.IO;
using UnityEngine;

public class TerrainType
{
	public class ResourceInfo
	{
		public ResourceInfo()
		{

		}

		public ResourceInfo(string un, float mod)
		{
			ResourceName = un;
			BaseModifier = mod;
		}

		public string ResourceName = "";
		public float BaseModifier = 0f;
	}

	public TerrainType()
	{

	}

	public TerrainType(string un, string fn, List<ResourceInfo> rs)
	{
		UniqueName = un;
		FriendlyName = fn;
		Resources.AddRange(rs);
	}

	public string UniqueName = "";
	public string FriendlyName = "";
	[XmlArrayItem("Resource")]
	public List<ResourceInfo> Resources = new List<ResourceInfo>();
}

