//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class StakeClaim : IAction
{
	public string ActionName { get { return "Stake Claim"; } }

	public StakeClaim ()
	{
	}

	public void Execute(HexTile target)
	{
		target.renderer.material.SetColor("_Color", Color.red);
	}
}

